// Code generated by protoc-gen-go. DO NOT EDIT.
// source: planet/planetpb/planet.proto

package planetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// We can define our planet and all of its corresponding data here, we can split this up later if we want.
type Planet struct {
	PlanetId             string          `protobuf:"bytes,1,opt,name=planet_id,json=planetId,proto3" json:"planet_id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Orbitalinfo          *OrbitalInfo    `protobuf:"bytes,3,opt,name=orbitalinfo,proto3" json:"orbitalinfo,omitempty"`
	Physicalinfo         *PhysicalInfo   `protobuf:"bytes,4,opt,name=physicalinfo,proto3" json:"physicalinfo,omitempty"`
	Atmosphereinfo       *AtmosphereInfo `protobuf:"bytes,5,opt,name=atmosphereinfo,proto3" json:"atmosphereinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Planet) Reset()         { *m = Planet{} }
func (m *Planet) String() string { return proto.CompactTextString(m) }
func (*Planet) ProtoMessage()    {}
func (*Planet) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{0}
}

func (m *Planet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Planet.Unmarshal(m, b)
}
func (m *Planet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Planet.Marshal(b, m, deterministic)
}
func (m *Planet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planet.Merge(m, src)
}
func (m *Planet) XXX_Size() int {
	return xxx_messageInfo_Planet.Size(m)
}
func (m *Planet) XXX_DiscardUnknown() {
	xxx_messageInfo_Planet.DiscardUnknown(m)
}

var xxx_messageInfo_Planet proto.InternalMessageInfo

func (m *Planet) GetPlanetId() string {
	if m != nil {
		return m.PlanetId
	}
	return ""
}

func (m *Planet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Planet) GetOrbitalinfo() *OrbitalInfo {
	if m != nil {
		return m.Orbitalinfo
	}
	return nil
}

func (m *Planet) GetPhysicalinfo() *PhysicalInfo {
	if m != nil {
		return m.Physicalinfo
	}
	return nil
}

func (m *Planet) GetAtmosphereinfo() *AtmosphereInfo {
	if m != nil {
		return m.Atmosphereinfo
	}
	return nil
}

type OrbitalInfo struct {
	Aphelion                 float64      `protobuf:"fixed64,1,opt,name=aphelion,proto3" json:"aphelion,omitempty"`
	Perihelion               float64      `protobuf:"fixed64,2,opt,name=perihelion,proto3" json:"perihelion,omitempty"`
	Semimajoraxis            float64      `protobuf:"fixed64,3,opt,name=semimajoraxis,proto3" json:"semimajoraxis,omitempty"`
	Eccentricity             float64      `protobuf:"fixed64,4,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	Orbitalperiod            float64      `protobuf:"fixed64,5,opt,name=orbitalperiod,proto3" json:"orbitalperiod,omitempty"`
	Synodicperiod            float64      `protobuf:"fixed64,6,opt,name=synodicperiod,proto3" json:"synodicperiod,omitempty"`
	Avgorbitalspeed          float64      `protobuf:"fixed64,7,opt,name=avgorbitalspeed,proto3" json:"avgorbitalspeed,omitempty"`
	Meananomaly              float64      `protobuf:"fixed64,8,opt,name=meananomaly,proto3" json:"meananomaly,omitempty"`
	Inclination              *Inclination `protobuf:"bytes,9,opt,name=inclination,proto3" json:"inclination,omitempty"`
	Longitudeofascendingnode float64      `protobuf:"fixed64,10,opt,name=longitudeofascendingnode,proto3" json:"longitudeofascendingnode,omitempty"`
	Satelites                uint32       `protobuf:"varint,11,opt,name=satelites,proto3" json:"satelites,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}     `json:"-"`
	XXX_unrecognized         []byte       `json:"-"`
	XXX_sizecache            int32        `json:"-"`
}

func (m *OrbitalInfo) Reset()         { *m = OrbitalInfo{} }
func (m *OrbitalInfo) String() string { return proto.CompactTextString(m) }
func (*OrbitalInfo) ProtoMessage()    {}
func (*OrbitalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{1}
}

func (m *OrbitalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrbitalInfo.Unmarshal(m, b)
}
func (m *OrbitalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrbitalInfo.Marshal(b, m, deterministic)
}
func (m *OrbitalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrbitalInfo.Merge(m, src)
}
func (m *OrbitalInfo) XXX_Size() int {
	return xxx_messageInfo_OrbitalInfo.Size(m)
}
func (m *OrbitalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrbitalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrbitalInfo proto.InternalMessageInfo

func (m *OrbitalInfo) GetAphelion() float64 {
	if m != nil {
		return m.Aphelion
	}
	return 0
}

func (m *OrbitalInfo) GetPerihelion() float64 {
	if m != nil {
		return m.Perihelion
	}
	return 0
}

func (m *OrbitalInfo) GetSemimajoraxis() float64 {
	if m != nil {
		return m.Semimajoraxis
	}
	return 0
}

func (m *OrbitalInfo) GetEccentricity() float64 {
	if m != nil {
		return m.Eccentricity
	}
	return 0
}

func (m *OrbitalInfo) GetOrbitalperiod() float64 {
	if m != nil {
		return m.Orbitalperiod
	}
	return 0
}

func (m *OrbitalInfo) GetSynodicperiod() float64 {
	if m != nil {
		return m.Synodicperiod
	}
	return 0
}

func (m *OrbitalInfo) GetAvgorbitalspeed() float64 {
	if m != nil {
		return m.Avgorbitalspeed
	}
	return 0
}

func (m *OrbitalInfo) GetMeananomaly() float64 {
	if m != nil {
		return m.Meananomaly
	}
	return 0
}

func (m *OrbitalInfo) GetInclination() *Inclination {
	if m != nil {
		return m.Inclination
	}
	return nil
}

func (m *OrbitalInfo) GetLongitudeofascendingnode() float64 {
	if m != nil {
		return m.Longitudeofascendingnode
	}
	return 0
}

func (m *OrbitalInfo) GetSatelites() uint32 {
	if m != nil {
		return m.Satelites
	}
	return 0
}

type PhysicalInfo struct {
	Meanradius                 string             `protobuf:"bytes,1,opt,name=meanradius,proto3" json:"meanradius,omitempty"`
	Equatorialradius           string             `protobuf:"bytes,2,opt,name=equatorialradius,proto3" json:"equatorialradius,omitempty"`
	Polarradius                string             `protobuf:"bytes,3,opt,name=polarradius,proto3" json:"polarradius,omitempty"`
	Flattening                 string             `protobuf:"bytes,4,opt,name=flattening,proto3" json:"flattening,omitempty"`
	Surfacearea                float64            `protobuf:"fixed64,5,opt,name=surfacearea,proto3" json:"surfacearea,omitempty"`
	Volume                     float64            `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Mass                       float64            `protobuf:"fixed64,7,opt,name=mass,proto3" json:"mass,omitempty"`
	Meandensity                float64            `protobuf:"fixed64,8,opt,name=meandensity,proto3" json:"meandensity,omitempty"`
	Surfacegravity             float64            `protobuf:"fixed64,9,opt,name=surfacegravity,proto3" json:"surfacegravity,omitempty"`
	Momentofinertiafactor      string             `protobuf:"bytes,10,opt,name=momentofinertiafactor,proto3" json:"momentofinertiafactor,omitempty"`
	Escapevelocity             float64            `protobuf:"fixed64,11,opt,name=escapevelocity,proto3" json:"escapevelocity,omitempty"`
	Siderealrotationperiod     float64            `protobuf:"fixed64,12,opt,name=siderealrotationperiod,proto3" json:"siderealrotationperiod,omitempty"`
	Equatorialrotationvelocity float64            `protobuf:"fixed64,13,opt,name=equatorialrotationvelocity,proto3" json:"equatorialrotationvelocity,omitempty"`
	Axialtilt                  float64            `protobuf:"fixed64,14,opt,name=axialtilt,proto3" json:"axialtilt,omitempty"`
	Northpolerightascension    float64            `protobuf:"fixed64,15,opt,name=northpolerightascension,proto3" json:"northpolerightascension,omitempty"`
	Northpoledeclination       float64            `protobuf:"fixed64,16,opt,name=northpoledeclination,proto3" json:"northpoledeclination,omitempty"`
	Albedo                     *Albedo            `protobuf:"bytes,17,opt,name=albedo,proto3" json:"albedo,omitempty"`
	Surfacetemp                *SurfaceTemp       `protobuf:"bytes,18,opt,name=surfacetemp,proto3" json:"surfacetemp,omitempty"`
	Apparentmagnitude          *ApparentMagnitude `protobuf:"bytes,19,opt,name=apparentmagnitude,proto3" json:"apparentmagnitude,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}           `json:"-"`
	XXX_unrecognized           []byte             `json:"-"`
	XXX_sizecache              int32              `json:"-"`
}

func (m *PhysicalInfo) Reset()         { *m = PhysicalInfo{} }
func (m *PhysicalInfo) String() string { return proto.CompactTextString(m) }
func (*PhysicalInfo) ProtoMessage()    {}
func (*PhysicalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{2}
}

func (m *PhysicalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhysicalInfo.Unmarshal(m, b)
}
func (m *PhysicalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhysicalInfo.Marshal(b, m, deterministic)
}
func (m *PhysicalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhysicalInfo.Merge(m, src)
}
func (m *PhysicalInfo) XXX_Size() int {
	return xxx_messageInfo_PhysicalInfo.Size(m)
}
func (m *PhysicalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PhysicalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PhysicalInfo proto.InternalMessageInfo

func (m *PhysicalInfo) GetMeanradius() string {
	if m != nil {
		return m.Meanradius
	}
	return ""
}

func (m *PhysicalInfo) GetEquatorialradius() string {
	if m != nil {
		return m.Equatorialradius
	}
	return ""
}

func (m *PhysicalInfo) GetPolarradius() string {
	if m != nil {
		return m.Polarradius
	}
	return ""
}

func (m *PhysicalInfo) GetFlattening() string {
	if m != nil {
		return m.Flattening
	}
	return ""
}

func (m *PhysicalInfo) GetSurfacearea() float64 {
	if m != nil {
		return m.Surfacearea
	}
	return 0
}

func (m *PhysicalInfo) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *PhysicalInfo) GetMass() float64 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *PhysicalInfo) GetMeandensity() float64 {
	if m != nil {
		return m.Meandensity
	}
	return 0
}

func (m *PhysicalInfo) GetSurfacegravity() float64 {
	if m != nil {
		return m.Surfacegravity
	}
	return 0
}

func (m *PhysicalInfo) GetMomentofinertiafactor() string {
	if m != nil {
		return m.Momentofinertiafactor
	}
	return ""
}

func (m *PhysicalInfo) GetEscapevelocity() float64 {
	if m != nil {
		return m.Escapevelocity
	}
	return 0
}

func (m *PhysicalInfo) GetSiderealrotationperiod() float64 {
	if m != nil {
		return m.Siderealrotationperiod
	}
	return 0
}

func (m *PhysicalInfo) GetEquatorialrotationvelocity() float64 {
	if m != nil {
		return m.Equatorialrotationvelocity
	}
	return 0
}

func (m *PhysicalInfo) GetAxialtilt() float64 {
	if m != nil {
		return m.Axialtilt
	}
	return 0
}

func (m *PhysicalInfo) GetNorthpolerightascension() float64 {
	if m != nil {
		return m.Northpolerightascension
	}
	return 0
}

func (m *PhysicalInfo) GetNorthpoledeclination() float64 {
	if m != nil {
		return m.Northpoledeclination
	}
	return 0
}

func (m *PhysicalInfo) GetAlbedo() *Albedo {
	if m != nil {
		return m.Albedo
	}
	return nil
}

func (m *PhysicalInfo) GetSurfacetemp() *SurfaceTemp {
	if m != nil {
		return m.Surfacetemp
	}
	return nil
}

func (m *PhysicalInfo) GetApparentmagnitude() *ApparentMagnitude {
	if m != nil {
		return m.Apparentmagnitude
	}
	return nil
}

type AtmosphereInfo struct {
	Surfacepressure      float64    `protobuf:"fixed64,1,opt,name=surfacepressure,proto3" json:"surfacepressure,omitempty"`
	Element              []*Element `protobuf:"bytes,2,rep,name=element,proto3" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AtmosphereInfo) Reset()         { *m = AtmosphereInfo{} }
func (m *AtmosphereInfo) String() string { return proto.CompactTextString(m) }
func (*AtmosphereInfo) ProtoMessage()    {}
func (*AtmosphereInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{3}
}

func (m *AtmosphereInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AtmosphereInfo.Unmarshal(m, b)
}
func (m *AtmosphereInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AtmosphereInfo.Marshal(b, m, deterministic)
}
func (m *AtmosphereInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AtmosphereInfo.Merge(m, src)
}
func (m *AtmosphereInfo) XXX_Size() int {
	return xxx_messageInfo_AtmosphereInfo.Size(m)
}
func (m *AtmosphereInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AtmosphereInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AtmosphereInfo proto.InternalMessageInfo

func (m *AtmosphereInfo) GetSurfacepressure() float64 {
	if m != nil {
		return m.Surfacepressure
	}
	return 0
}

func (m *AtmosphereInfo) GetElement() []*Element {
	if m != nil {
		return m.Element
	}
	return nil
}

type Element struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Percentasdecimal     float64  `protobuf:"fixed64,2,opt,name=percentasdecimal,proto3" json:"percentasdecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}
func (*Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{4}
}

func (m *Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Element.Unmarshal(m, b)
}
func (m *Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Element.Marshal(b, m, deterministic)
}
func (m *Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Element.Merge(m, src)
}
func (m *Element) XXX_Size() int {
	return xxx_messageInfo_Element.Size(m)
}
func (m *Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Element proto.InternalMessageInfo

func (m *Element) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Element) GetPercentasdecimal() float64 {
	if m != nil {
		return m.Percentasdecimal
	}
	return 0
}

type SurfaceTemp struct {
	Min                  int32    `protobuf:"zigzag32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"zigzag32,2,opt,name=max,proto3" json:"max,omitempty"`
	Mean                 int32    `protobuf:"zigzag32,3,opt,name=mean,proto3" json:"mean,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurfaceTemp) Reset()         { *m = SurfaceTemp{} }
func (m *SurfaceTemp) String() string { return proto.CompactTextString(m) }
func (*SurfaceTemp) ProtoMessage()    {}
func (*SurfaceTemp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{5}
}

func (m *SurfaceTemp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurfaceTemp.Unmarshal(m, b)
}
func (m *SurfaceTemp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurfaceTemp.Marshal(b, m, deterministic)
}
func (m *SurfaceTemp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurfaceTemp.Merge(m, src)
}
func (m *SurfaceTemp) XXX_Size() int {
	return xxx_messageInfo_SurfaceTemp.Size(m)
}
func (m *SurfaceTemp) XXX_DiscardUnknown() {
	xxx_messageInfo_SurfaceTemp.DiscardUnknown(m)
}

var xxx_messageInfo_SurfaceTemp proto.InternalMessageInfo

func (m *SurfaceTemp) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *SurfaceTemp) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *SurfaceTemp) GetMean() int32 {
	if m != nil {
		return m.Mean
	}
	return 0
}

type ApparentMagnitude struct {
	Min                  float64  `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64  `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApparentMagnitude) Reset()         { *m = ApparentMagnitude{} }
func (m *ApparentMagnitude) String() string { return proto.CompactTextString(m) }
func (*ApparentMagnitude) ProtoMessage()    {}
func (*ApparentMagnitude) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{6}
}

func (m *ApparentMagnitude) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApparentMagnitude.Unmarshal(m, b)
}
func (m *ApparentMagnitude) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApparentMagnitude.Marshal(b, m, deterministic)
}
func (m *ApparentMagnitude) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApparentMagnitude.Merge(m, src)
}
func (m *ApparentMagnitude) XXX_Size() int {
	return xxx_messageInfo_ApparentMagnitude.Size(m)
}
func (m *ApparentMagnitude) XXX_DiscardUnknown() {
	xxx_messageInfo_ApparentMagnitude.DiscardUnknown(m)
}

var xxx_messageInfo_ApparentMagnitude proto.InternalMessageInfo

func (m *ApparentMagnitude) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ApparentMagnitude) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

type Inclination struct {
	Ecliptic             float64  `protobuf:"fixed64,1,opt,name=ecliptic,proto3" json:"ecliptic,omitempty"`
	Sunsequator          float64  `protobuf:"fixed64,2,opt,name=sunsequator,proto3" json:"sunsequator,omitempty"`
	Invariableplane      float64  `protobuf:"fixed64,3,opt,name=invariableplane,proto3" json:"invariableplane,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inclination) Reset()         { *m = Inclination{} }
func (m *Inclination) String() string { return proto.CompactTextString(m) }
func (*Inclination) ProtoMessage()    {}
func (*Inclination) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{7}
}

func (m *Inclination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inclination.Unmarshal(m, b)
}
func (m *Inclination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inclination.Marshal(b, m, deterministic)
}
func (m *Inclination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inclination.Merge(m, src)
}
func (m *Inclination) XXX_Size() int {
	return xxx_messageInfo_Inclination.Size(m)
}
func (m *Inclination) XXX_DiscardUnknown() {
	xxx_messageInfo_Inclination.DiscardUnknown(m)
}

var xxx_messageInfo_Inclination proto.InternalMessageInfo

func (m *Inclination) GetEcliptic() float64 {
	if m != nil {
		return m.Ecliptic
	}
	return 0
}

func (m *Inclination) GetSunsequator() float64 {
	if m != nil {
		return m.Sunsequator
	}
	return 0
}

func (m *Inclination) GetInvariableplane() float64 {
	if m != nil {
		return m.Invariableplane
	}
	return 0
}

type Albedo struct {
	Geometric            float64  `protobuf:"fixed64,1,opt,name=geometric,proto3" json:"geometric,omitempty"`
	Bond                 float64  `protobuf:"fixed64,2,opt,name=bond,proto3" json:"bond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Albedo) Reset()         { *m = Albedo{} }
func (m *Albedo) String() string { return proto.CompactTextString(m) }
func (*Albedo) ProtoMessage()    {}
func (*Albedo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{8}
}

func (m *Albedo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Albedo.Unmarshal(m, b)
}
func (m *Albedo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Albedo.Marshal(b, m, deterministic)
}
func (m *Albedo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Albedo.Merge(m, src)
}
func (m *Albedo) XXX_Size() int {
	return xxx_messageInfo_Albedo.Size(m)
}
func (m *Albedo) XXX_DiscardUnknown() {
	xxx_messageInfo_Albedo.DiscardUnknown(m)
}

var xxx_messageInfo_Albedo proto.InternalMessageInfo

func (m *Albedo) GetGeometric() float64 {
	if m != nil {
		return m.Geometric
	}
	return 0
}

func (m *Albedo) GetBond() float64 {
	if m != nil {
		return m.Bond
	}
	return 0
}

type ReadPlanetRequest struct {
	PlanetId             string   `protobuf:"bytes,1,opt,name=planet_id,json=planetId,proto3" json:"planet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPlanetRequest) Reset()         { *m = ReadPlanetRequest{} }
func (m *ReadPlanetRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPlanetRequest) ProtoMessage()    {}
func (*ReadPlanetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{9}
}

func (m *ReadPlanetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPlanetRequest.Unmarshal(m, b)
}
func (m *ReadPlanetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPlanetRequest.Marshal(b, m, deterministic)
}
func (m *ReadPlanetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPlanetRequest.Merge(m, src)
}
func (m *ReadPlanetRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPlanetRequest.Size(m)
}
func (m *ReadPlanetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPlanetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPlanetRequest proto.InternalMessageInfo

func (m *ReadPlanetRequest) GetPlanetId() string {
	if m != nil {
		return m.PlanetId
	}
	return ""
}

type ReadPlanetResponse struct {
	Planet               *Planet  `protobuf:"bytes,1,opt,name=planet,proto3" json:"planet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPlanetResponse) Reset()         { *m = ReadPlanetResponse{} }
func (m *ReadPlanetResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPlanetResponse) ProtoMessage()    {}
func (*ReadPlanetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e7ae48ba9b9a6fb, []int{10}
}

func (m *ReadPlanetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPlanetResponse.Unmarshal(m, b)
}
func (m *ReadPlanetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPlanetResponse.Marshal(b, m, deterministic)
}
func (m *ReadPlanetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPlanetResponse.Merge(m, src)
}
func (m *ReadPlanetResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPlanetResponse.Size(m)
}
func (m *ReadPlanetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPlanetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPlanetResponse proto.InternalMessageInfo

func (m *ReadPlanetResponse) GetPlanet() *Planet {
	if m != nil {
		return m.Planet
	}
	return nil
}

func init() {
	proto.RegisterType((*Planet)(nil), "planet.Planet")
	proto.RegisterType((*OrbitalInfo)(nil), "planet.OrbitalInfo")
	proto.RegisterType((*PhysicalInfo)(nil), "planet.PhysicalInfo")
	proto.RegisterType((*AtmosphereInfo)(nil), "planet.AtmosphereInfo")
	proto.RegisterType((*Element)(nil), "planet.Element")
	proto.RegisterType((*SurfaceTemp)(nil), "planet.SurfaceTemp")
	proto.RegisterType((*ApparentMagnitude)(nil), "planet.ApparentMagnitude")
	proto.RegisterType((*Inclination)(nil), "planet.Inclination")
	proto.RegisterType((*Albedo)(nil), "planet.Albedo")
	proto.RegisterType((*ReadPlanetRequest)(nil), "planet.ReadPlanetRequest")
	proto.RegisterType((*ReadPlanetResponse)(nil), "planet.ReadPlanetResponse")
}

func init() {
	proto.RegisterFile("planet/planetpb/planet.proto", fileDescriptor_4e7ae48ba9b9a6fb)
}

var fileDescriptor_4e7ae48ba9b9a6fb = []byte{
	// 940 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0xdd, 0x6e, 0x1b, 0x37,
	0x13, 0xc5, 0xda, 0xf9, 0x64, 0x6b, 0xe4, 0x3f, 0x31, 0xf9, 0xdc, 0xad, 0x1b, 0x14, 0xc2, 0xa2,
	0x08, 0xd4, 0x5c, 0xa4, 0x85, 0xfb, 0x17, 0x04, 0x45, 0x80, 0xb6, 0x08, 0x0a, 0x5f, 0x14, 0x0d,
	0x36, 0xb9, 0xea, 0x4d, 0x31, 0xda, 0x1d, 0x49, 0x2c, 0xb8, 0xe4, 0x86, 0xa4, 0x04, 0xfb, 0xdd,
	0x8a, 0x3e, 0x50, 0x9f, 0xa2, 0xe0, 0x2c, 0x25, 0x51, 0x92, 0x9d, 0x2b, 0x91, 0xe7, 0x9c, 0x99,
	0x59, 0x72, 0x0e, 0x49, 0xc1, 0xd3, 0x56, 0xa1, 0x26, 0xff, 0x55, 0xf7, 0xd3, 0x4e, 0xe2, 0xe0,
	0x45, 0x6b, 0x8d, 0x37, 0xa2, 0xd7, 0xcd, 0x8a, 0x7f, 0x33, 0xe8, 0xbd, 0xe5, 0xa1, 0xf8, 0x0c,
	0xfa, 0x1d, 0xf8, 0xa7, 0xac, 0xf3, 0x6c, 0x94, 0x8d, 0xfb, 0xe5, 0x71, 0x07, 0xdc, 0xd4, 0x42,
	0xc0, 0x23, 0x8d, 0x0d, 0xe5, 0x07, 0x8c, 0xf3, 0x58, 0x7c, 0x07, 0x03, 0x63, 0x27, 0xd2, 0xa3,
	0x92, 0x7a, 0x6a, 0xf2, 0xc3, 0x51, 0x36, 0x1e, 0x5c, 0x3f, 0x7e, 0x11, 0xeb, 0xfc, 0xde, 0x51,
	0x37, 0x7a, 0x6a, 0xca, 0x54, 0x27, 0x5e, 0xc2, 0x49, 0x3b, 0xbf, 0x73, 0xb2, 0x8a, 0x71, 0x8f,
	0x38, 0xee, 0xc9, 0x2a, 0xee, 0x6d, 0xe4, 0x38, 0x70, 0x4b, 0x29, 0x5e, 0xc3, 0x19, 0xfa, 0xc6,
	0xb8, 0x76, 0x4e, 0x96, 0x38, 0xf6, 0x7f, 0x1c, 0x7b, 0xb9, 0x8a, 0xfd, 0x69, 0xcd, 0x72, 0xf4,
	0x8e, 0xba, 0xf8, 0xfb, 0x10, 0x06, 0xc9, 0x67, 0x89, 0x2b, 0x38, 0xc6, 0x76, 0x4e, 0x4a, 0x1a,
	0xcd, 0x0b, 0xce, 0xca, 0xf5, 0x5c, 0x7c, 0x0e, 0xd0, 0x92, 0x95, 0x91, 0x3d, 0x60, 0x36, 0x41,
	0xc4, 0x17, 0x70, 0xea, 0xa8, 0x91, 0x0d, 0xfe, 0x65, 0x2c, 0xde, 0x4a, 0xc7, 0xcb, 0xcf, 0xca,
	0x6d, 0x50, 0x14, 0x70, 0x42, 0x55, 0x45, 0xda, 0x5b, 0x59, 0x49, 0x7f, 0xc7, 0x6b, 0xcd, 0xca,
	0x2d, 0x2c, 0x64, 0x8a, 0xdb, 0x13, 0xd2, 0x9b, 0x9a, 0x17, 0x95, 0x95, 0xdb, 0x20, 0xd7, 0xbb,
	0xd3, 0xa6, 0x96, 0x55, 0x54, 0xf5, 0x62, 0xbd, 0x14, 0x14, 0x63, 0x38, 0xc7, 0xe5, 0x2c, 0x46,
	0xba, 0x96, 0xa8, 0xce, 0x8f, 0x58, 0xb7, 0x0b, 0x8b, 0x11, 0x0c, 0x1a, 0x42, 0x8d, 0xda, 0x34,
	0xa8, 0xee, 0xf2, 0x63, 0x56, 0xa5, 0x50, 0x68, 0xaf, 0xd4, 0x95, 0x92, 0x1a, 0x7d, 0xd8, 0x82,
	0xfe, 0x76, 0x7b, 0x6f, 0x36, 0x54, 0x99, 0xea, 0xc4, 0x2b, 0xc8, 0x95, 0xd1, 0x33, 0xe9, 0x17,
	0x35, 0x99, 0x29, 0xba, 0x8a, 0x74, 0x2d, 0xf5, 0x4c, 0x9b, 0x9a, 0x72, 0xe0, 0x2a, 0x0f, 0xf2,
	0xe2, 0x29, 0xf4, 0x1d, 0x7a, 0x52, 0xd2, 0x93, 0xcb, 0x07, 0xa3, 0x6c, 0x7c, 0x5a, 0x6e, 0x80,
	0xe2, 0x9f, 0x1e, 0x9c, 0xa4, 0xee, 0x08, 0x3d, 0x0a, 0x1f, 0x6c, 0xb1, 0x96, 0x0b, 0x17, 0x2d,
	0x9b, 0x20, 0xe2, 0x39, 0x5c, 0xd0, 0x87, 0x05, 0x7a, 0x63, 0x25, 0xaa, 0xa8, 0xea, 0x0c, 0xbc,
	0x87, 0x87, 0xfd, 0x68, 0x8d, 0x42, 0x1b, 0x65, 0x87, 0x2c, 0x4b, 0xa1, 0x50, 0x6d, 0xaa, 0xd0,
	0x7b, 0xd2, 0x52, 0xcf, 0xb8, 0x93, 0xfd, 0x32, 0x41, 0x42, 0x06, 0xb7, 0xb0, 0x53, 0xac, 0x08,
	0x2d, 0x61, 0xec, 0x62, 0x0a, 0x89, 0x4b, 0xe8, 0x2d, 0x8d, 0x5a, 0x34, 0x14, 0x9b, 0x17, 0x67,
	0xe1, 0x70, 0x35, 0xe8, 0x5c, 0x6c, 0x15, 0x8f, 0x57, 0xfd, 0xa9, 0x49, 0xbb, 0x60, 0x9c, 0xa4,
	0x3f, 0x11, 0x12, 0xcf, 0xe0, 0x2c, 0x26, 0x9f, 0x59, 0x5c, 0x06, 0x51, 0x9f, 0x45, 0x3b, 0xa8,
	0xf8, 0x16, 0xfe, 0xdf, 0x98, 0x86, 0xb4, 0x37, 0x53, 0xa9, 0xc9, 0x7a, 0x89, 0x53, 0xac, 0xbc,
	0xb1, 0xdc, 0x8d, 0x7e, 0x79, 0x3f, 0x19, 0xb2, 0x93, 0xab, 0xb0, 0xa5, 0x25, 0x29, 0xc3, 0xde,
	0x1d, 0x74, 0xd9, 0xb7, 0x51, 0xf1, 0x3d, 0x5c, 0x3a, 0x59, 0x93, 0x25, 0x54, 0xd6, 0x78, 0xb6,
	0x40, 0x34, 0xe8, 0x09, 0xeb, 0x1f, 0x60, 0xc5, 0x6b, 0xb8, 0x4a, 0x7a, 0x10, 0xb9, 0x75, 0xad,
	0x53, 0x8e, 0xfd, 0x88, 0x22, 0x58, 0x05, 0x6f, 0x25, 0x2a, 0x2f, 0x95, 0xcf, 0xcf, 0x58, 0xbe,
	0x01, 0xc4, 0x4b, 0xf8, 0x44, 0x1b, 0xeb, 0xe7, 0xad, 0x51, 0x64, 0xe5, 0x6c, 0xee, 0xd9, 0x67,
	0x2e, 0xf8, 0xf8, 0x9c, 0xb5, 0x0f, 0xd1, 0xe2, 0x1a, 0x9e, 0xac, 0xa9, 0x9a, 0x36, 0xf6, 0xbf,
	0xe0, 0xb0, 0x7b, 0x39, 0xf1, 0x0c, 0x7a, 0xa8, 0x26, 0x54, 0x9b, 0x7c, 0xc8, 0x87, 0xe4, 0x6c,
	0x7d, 0x1f, 0x31, 0x5a, 0x46, 0x36, 0x9c, 0xa8, 0xd8, 0x1b, 0x4f, 0x4d, 0x9b, 0x8b, 0xed, 0x13,
	0xf5, 0xae, 0xa3, 0xde, 0x53, 0xd3, 0x96, 0xa9, 0x4e, 0xfc, 0x0a, 0x43, 0x6c, 0x5b, 0xb4, 0xa4,
	0x7d, 0x83, 0x33, 0xcd, 0x27, 0x27, 0x7f, 0xcc, 0xc1, 0x9f, 0xae, 0x2b, 0x45, 0xc1, 0x6f, 0x2b,
	0x41, 0xb9, 0x1f, 0x53, 0x10, 0x9c, 0x6d, 0xdf, 0x90, 0xe1, 0xbe, 0x88, 0x95, 0x5a, 0x4b, 0xce,
	0x2d, 0x2c, 0xc5, 0x8b, 0x70, 0x17, 0x16, 0x5f, 0xc2, 0x11, 0x29, 0x0a, 0x4e, 0xc9, 0x0f, 0x46,
	0x87, 0xe3, 0xc1, 0xf5, 0xf9, 0xaa, 0xf4, 0x9b, 0x0e, 0x2e, 0x57, 0x7c, 0x71, 0x03, 0x47, 0x11,
	0x5b, 0x3f, 0x1b, 0x59, 0xf2, 0x6c, 0x3c, 0x87, 0x8b, 0x96, 0x6c, 0xb8, 0x00, 0xd1, 0xd5, 0x54,
	0xc9, 0x06, 0x55, 0xbc, 0x5f, 0xf7, 0xf0, 0xe2, 0x0d, 0x0c, 0x92, 0x6d, 0x11, 0x17, 0x70, 0xd8,
	0xc8, 0xee, 0xae, 0x1e, 0x96, 0x61, 0xc8, 0x08, 0xde, 0x72, 0x7c, 0x40, 0xf0, 0x96, 0x0f, 0x13,
	0xa1, 0xe6, 0x13, 0x3c, 0x2c, 0x79, 0x5c, 0xfc, 0x00, 0xc3, 0xbd, 0x0d, 0x4a, 0x93, 0x65, 0x7b,
	0xc9, 0x32, 0x4e, 0x56, 0x2c, 0x60, 0x90, 0x5c, 0x74, 0xe1, 0xc1, 0x08, 0x6d, 0x6f, 0xbd, 0xac,
	0x56, 0x0f, 0xc6, 0x6a, 0xde, 0x1d, 0x7f, 0xed, 0xa2, 0x65, 0x63, 0x92, 0x14, 0x0a, 0x9b, 0x2d,
	0xf5, 0x12, 0xad, 0xc4, 0x89, 0x22, 0xde, 0xbc, 0xf8, 0x68, 0xec, 0xc2, 0xc5, 0x2b, 0xe8, 0x75,
	0xd6, 0x09, 0x36, 0x9f, 0x91, 0x69, 0x28, 0x3c, 0x16, 0xb1, 0xe4, 0x06, 0x08, 0x6b, 0x9d, 0x18,
	0x5d, 0xc7, 0x62, 0x3c, 0x2e, 0xbe, 0x86, 0x61, 0x49, 0x58, 0x77, 0x8f, 0x7a, 0x49, 0x1f, 0x16,
	0xe4, 0x3e, 0xfe, 0xb6, 0x17, 0x3f, 0x82, 0x48, 0x23, 0x5c, 0x6b, 0xb4, 0xa3, 0x60, 0xea, 0x4e,
	0xc1, 0xfa, 0xc4, 0xd4, 0x51, 0x17, 0xd9, 0xeb, 0xf7, 0x70, 0xda, 0x21, 0xef, 0xc8, 0x2e, 0x65,
	0x45, 0xe2, 0x17, 0x80, 0x4d, 0x3a, 0xb1, 0x76, 0xe8, 0xde, 0x47, 0x5d, 0x5d, 0xdd, 0x47, 0x75,
	0xd5, 0x7f, 0x86, 0x3f, 0x8e, 0x57, 0x7f, 0x5c, 0x26, 0x3d, 0xfe, 0xcb, 0xf2, 0xcd, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x45, 0x31, 0x98, 0x95, 0xd2, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlanetServiceClient is the client API for PlanetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlanetServiceClient interface {
	ReadPlanet(ctx context.Context, in *ReadPlanetRequest, opts ...grpc.CallOption) (*ReadPlanetResponse, error)
}

type planetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanetServiceClient(cc grpc.ClientConnInterface) PlanetServiceClient {
	return &planetServiceClient{cc}
}

func (c *planetServiceClient) ReadPlanet(ctx context.Context, in *ReadPlanetRequest, opts ...grpc.CallOption) (*ReadPlanetResponse, error) {
	out := new(ReadPlanetResponse)
	err := c.cc.Invoke(ctx, "/planet.PlanetService/ReadPlanet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanetServiceServer is the server API for PlanetService service.
type PlanetServiceServer interface {
	ReadPlanet(context.Context, *ReadPlanetRequest) (*ReadPlanetResponse, error)
}

// UnimplementedPlanetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlanetServiceServer struct {
}

func (*UnimplementedPlanetServiceServer) ReadPlanet(ctx context.Context, req *ReadPlanetRequest) (*ReadPlanetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlanet not implemented")
}

func RegisterPlanetServiceServer(s *grpc.Server, srv PlanetServiceServer) {
	s.RegisterService(&_PlanetService_serviceDesc, srv)
}

func _PlanetService_ReadPlanet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPlanetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetServiceServer).ReadPlanet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planet.PlanetService/ReadPlanet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetServiceServer).ReadPlanet(ctx, req.(*ReadPlanetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlanetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "planet.PlanetService",
	HandlerType: (*PlanetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPlanet",
			Handler:    _PlanetService_ReadPlanet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "planet/planetpb/planet.proto",
}
